#1A
def wrong_add_function(arg1,arg2):
   arg1_index=0
   correct_ans=[2,3,4]
   while arg1_index < len(arg1):
      arg_2_sum = 0
      for arg2_elements in arg2:
          arg_2_sum = sum([arg1[arg1_index]+i for i in arg2])
        
      arg1[arg1_index]=arg_2_sum
      arg1_index+=1
   print(f"We are making an error in the 'while' loop.") #I couldn't put the print statement in the loop without making it repeat multiple times.
   print(f"The correct answer is {correct_ans}.")
   return arg1

arg1 = [1,2,3]
arg2 = [1,1,1]

wrong_add_function(arg1, arg2) #Should print where the error message is and what the correct answer is. No other changes were made so you also get the wrong output.



#1B
def correct_add_function(arg1,arg2):
   arg1_index=0
   while arg1_index < len(arg1):
      arg_2_sum = 0
      for arg2_elements in arg2:
          arg_2_sum = [arg1[arg1_index]+i for i in arg2] #I removed the sum
      arg1[arg1_index]=arg_2_sum[0] #I added a specific index of 0
      arg1_index+=1
   return arg1

arg1 = [1,2,3]
arg2 = [1,1,1]

correct_add_function(arg1, arg2) #This is the correct code where you should get [2,3,4]

#2A
#The code of 2B and 2C will be updated with the correct code from 1B.

#2B
def correction_add_function(arg1,arg2):
    try:
        for arg in arg1, arg2:
            for i, j in enumerate(arg):
                if isinstance(j, int):
                    #print('j type is an integer')
                    pass
                else:
                    #print('J type is not a integer')
                    raise Exception(f"{j} is not an integer")
#            print(f"I is {i}, j type is ",type(j))
        arg1_index=0
        while arg1_index < len(arg1):
           arg_2_sum = 0
           for arg2_elements in arg2:
              arg_2_sum = [arg1[arg1_index]+arg2[arg1_index]]
           arg1[arg1_index]=arg_2_sum[0]
           arg1_index+=1
        return arg1
    except:
        print(f" Your input argument {arg}, at element {i} is not of the expected type. Please change this and rerun.")

arg1=[1,2,3]
arg2=[3,'4',5] #We weren't given specific numbers for this one, so I created 2 lists, one that would trigger the exception.
correction_add_function(arg1, arg2)     #Should give an error message for arg2 at index1 for '4'



#2C
def correction_add_function(arg1,arg2):
    try:
        for arg in arg1, arg2:
            for i, j in enumerate(arg):
                if isinstance(j, int):
                    
                    pass
                else:
                    
                    raise Exception("They are not all integers")
#Numeric section
        arg1_index=0
        while arg1_index < len(arg1):
           arg_2_sum = 0
           for arg2_elements in arg2:
              arg_2_sum = [arg1[arg1_index]+arg2[arg1_index]]
           arg1[arg1_index]=arg_2_sum[0]  
           arg1_index+=1
        #print(arg1)
        return arg1
        
    except: #String section
        for i in range(len(arg2)):
            arg2[i] = str(arg2[i])
            
        for i in range(len(arg1)):
            arg1[i] = str(arg1[i])
            
        arg1_index=0
        arg_2_sum = ''
        arg_2_sum = ''.join(arg2)
        #print(arg_2_sum)

      
        arg1[0]=arg1[0]+str(arg_2_sum) #This could be done with a loop, but it was giving me multiples and this technically also works.
        arg1_index+=1
        arg1[1]=arg1[1]+str(arg_2_sum)
        arg1_index+=1
        arg1[2]=arg1[2]+str(arg_2_sum)
        arg1_index+=1
        #print(arg1)
        return arg1
    

arg1=[1,2,3]
arg2=[3,'4',5]
correction_add_function(arg1,arg2) #For string: expect output of 1345,2345,3345. For integer, expect sum instead.
    
    


